@startuml TwiitDisplay

Main -- RunCommand
CommandAbstract -- Main
ActivePlayer -- Main


ActivePlayer "1" o-- "2" Player :集約
Player "1" o-- "1..*" Monster :集約
Monster "1" o-- "1..*" Technique :集約
Monster "1" o-- "1" Type :集約

CommandAbstract <|-- CommandAction :汎化
CommandAbstract <|-- CommandButtole :汎化

Monster  <|-- FushigidaneMonster : 汎化
Monster  <|-- HitokageMonster : 汎化
Monster  <|-- MizugameMonster : 汎化

Technique  <|.. TechniqueTackle : 実現
Technique  <|.. techniqueHinoko : 実現
Technique  <|.. techniqueVineWhip : 実現
Technique  <|.. techniqueWaterGun : 実現

Type <|.. TypeFire : 実現
Type <|.. TypeWater : 実現
Type <|.. TypeGrass : 実現
Type <|.. TypeNomal : 実現


@enduml
