@startuml TwiitDisplay

class RunCommand{
    + run()
}
class Main{
    + start()
}

class WonMonster{
    + monsterList:Monster[]
    + getMonster():Monster
}

interface Monster <<interface>>{
    + name:string
    + hitPoint:number
    + technique: TechniqueList
}
class FushigidaneMonster {
}
class ActiveMonster{
}
abstract class CommandAbstract{
}

class CommandAction{
}
class CommandButtole{
}
class Technique{
}
class TechniqueTackle{
}


Main --> RunCommand
WonMonster --> Main
CommandAbstract --> Main
ActiveMonster --> Main
Monster --> Damage
Damage --> Main
WonMonster "1" o-- "1..*" Monster

TechniqueList "1" o-- "1..*" Technique

Monster <|.. TechniqueList :依存

Monster  <|.. FushigidaneMonster : 実現
Monster  <|.. HitokageMonster : 実現
Monster  <|.. MizugameMonster : 実現


CommandAbstract <|-- CommandAction :汎化
CommandAbstract <|-- CommandButtole :汎化
CommandButtole <-- Monster

Technique  <|.. TechniqueTackle : 実現
Technique  <|.. techniqueHinoko : 実現
Technique  <|.. techniqueVineWhip : 実現
Technique  <|.. techniqueWaterGun : 実現


@enduml
